name: tp0
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server/config.ini:/config.ini
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  client1:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client/config.yaml:/config.yaml
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Juan
      - APELLIDO=Perez
      - NACIMIENTO=1990-01-18
      - DOCUMENTO=30465798
      - NUMERO=3177
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
